services:
  mongo:
    image: mongo:8.2.9
    container_name: curevo-mongo
    restart: unless-stopped
    ports:
      - "27017:27017"
    volumes:
      - curevo-mongo-data:/data/db

volumes:
  curevo-mongo-data:
