const sections = [
  ["Data we handle", "Account data may include your name, email, password hash or Google account identifier, profile image, phone, location, date of birth, and biography. Product data may include focus sessions, routine names and schedules, reflections, notification preferences, feedback, support requests, consent records, sessions, and security audit events."],
  ["Why it is used", "Curevo uses this information to authenticate your account, save your personal focus workspace, show your routines and reflections, deliver reminders you enable, protect the service, respond to feedback, and meet account export or deletion requests."],
  ["Sensitive notes", "Reflection text can feel personal even though Curevo is not a medical service. Write only what you are comfortable storing in a prototype. Do not use Curevo for emergency communication or as a health record."],
  ["Providers", "MongoDB stores application data. Cloudinary may store profile images. Configured email and Google sign-in providers process the information needed for those features. Provider contracts, regions, backups, and production retention remain launch blockers."],
  ["Access, export, correction, and deletion", "Signed-in members can update profile details, download a JSON export, or permanently delete personal focus data from Profile. Profile-image removal from the active provider is attempted during deletion; deletion from infrastructure backups still requires verified production policy."],
  ["Retention and safety", "Session, token, support, privacy-request, and audit records use documented retention controls. Final legal retention periods and privacy contacts are not approved. Review deployments must use synthetic information."],
];

export default function PrivacyPage() {
  return <main className="min-h-screen bg-background pb-24 pt-32 text-foreground"><article className="mx-auto max-w-4xl px-5"><p className="text-xs font-bold uppercase tracking-[0.2em] text-primary">Privacy notice · prototype</p><h1 className="mt-4 text-5xl font-semibold tracking-[-0.05em] sm:text-7xl">Your personal space should not be mysterious.</h1><p className="mt-6 text-lg leading-8 text-muted-foreground">This interim notice describes the current source code and review environment. It is not final legal approval for public launch.</p><div className="mt-12 divide-y divide-border border-y">{sections.map(([title, text]) => <section key={title} className="grid gap-3 py-8 sm:grid-cols-[220px_1fr]"><h2 className="font-semibold">{title}</h2><p className="leading-7 text-muted-foreground">{text}</p></section>)}</div><p className="mt-8 rounded-2xl border border-amber-300/40 bg-amber-100/50 p-5 text-sm leading-6 dark:border-amber-800/40 dark:bg-amber-950/30">There is no approved privacy contact or operating entity yet. Do not submit real sensitive information until those details and the deployed infrastructure are verified.</p></article></main>;
}
