'use client';
import { useState } from 'react';
import Link from 'next/link';
import { ArrowDown, ArrowRight, ArrowUpRight, Globe2, ShieldCheck } from 'lucide-react';
import { emotions } from '@/lib/taxonomy';
import type { Pulse, FeedResult, CurevoEvent } from '@/lib/types';
import { useResource } from '@/lib/client';
import { useCurevo } from './curevo-provider';
import PulseChart from './pulse-chart';
import ThoughtCard from './thought-card';
import HumanityArt from './humanity-art';
export default function Home(){
 const {openCheckIn,identity}=useCurevo();const [filter,setFilter]=useState('');
 const {data:pulse,error:pulseError,loading:pulseLoading,refresh}=useResource<Pulse>('/api/pulse');
 const {data:feed,error:feedError,loading:feedLoading}=useResource<FeedResult>(`/api/checkins${filter?`?emotion=${filter}`:''}`);
 const {data:eventData}=useResource<{events:CurevoEvent[]}>('/api/events');
 return <>
 <section className="hero page-shell"><div className="hero-copy"><div className="eyebrow"><span className="tiny-cross">✳</span> A PLACE FOR EVERY FEELING</div><h1>Humanity,<br/><span>right now.</span></h1><p className="hero-description">A thousand different lives.<br/>A few feelings we all know.</p><p className="hero-support">Share what’s on your mind. Discover what’s on everyone else’s. Anonymously, honestly, together.</p><button className="button button-dark button-large" onClick={()=>openCheckIn()}>How are you feeling? <ArrowUpRight size={22}/></button><div className="hero-footnote"><ShieldCheck size={17}/><span>No account needed. Always anonymous to others.</span></div></div><div className="hero-art-panel"><div className="art-corner-label">INDIVIDUAL FEELINGS.<br/>A SHARED HUMAN EXPERIENCE.</div><HumanityArt/><div className="art-caption"><span>Different lives. Familiar feelings.</span><span aria-hidden="true">↗</span></div></div></section>
 <div className="page-shell intro-strip"><span><span className="status-dot"/>{identity?.realtimeEnabled?'A living portrait of how we feel':'A shared portrait of how we feel'}</span><a href="#pulse">Meet the Pulse <ArrowDown size={18}/></a></div>
 <section className="pulse-section" id="pulse"><div className="page-shell"><div className="section-heading"><div><div className="eyebrow">THE COLLECTIVE PICTURE</div><h2>What’s in the air?</h2></div><span className="time-window"><Globe2 size={17}/> Everyone · Past 24 hours</span></div><div className="pulse-layout"><div className="pulse-intro"><div className="pulse-count">{pulseLoading?'—':pulse?.participants.toLocaleString()??'—'}<span>people in the Pulse</span></div><p>A small window into a very human world. These are the feelings people chose to share.</p><button className="link-button" onClick={()=>openCheckIn()}>Add your feeling <ArrowUpRight size={20}/></button><div className="pulse-method"><span>01 — A feeling, not a diagnosis.</span><span>02 — Participants, not all of humanity.</span><span>03 — Real check-ins. Never made-up numbers.</span></div></div><div className="pulse-data">{pulseError?<div className="empty-state"><span className="empty-symbol">〰</span><h3>The Pulse is taking a moment.</h3><p>{pulseError}</p><button className="button button-secondary" onClick={refresh}>Try again</button></div>:pulse?<PulseChart pulse={pulse} compact/>:<div className="skeleton-chart" aria-label="Loading pulse">{Array.from({length:6},(_,i)=><div key={i}/>)}</div>}</div></div></div></section>
 <section className="feelings-section page-shell"><div className="section-heading"><div><div className="eyebrow">THERE’S NO WRONG ANSWER</div><h2>What’s your feeling?</h2></div><p>Start wherever you are.</p></div><div className="feeling-tiles">{['love','anxious','hopeful','lonely','grateful','overwhelmed'].map(slug=>{const e=emotions.find(e=>e.slug===slug)!;return <button key={slug} className="feeling-tile" onClick={()=>openCheckIn(slug)} style={{'--tile-color':e.color} as React.CSSProperties}><span className="tile-symbol" aria-hidden="true">{e.symbol}</span><span>{e.name}</span><ArrowUpRight size={20}/></button>;})}</div><button className="link-button all-feelings" onClick={()=>openCheckIn()}>Make room for another feeling <ArrowRight size={18}/></button></section>
 <section className="thoughts-section page-shell"><div className="section-heading"><div><div className="eyebrow">REAL PEOPLE. REAL INNER WORLDS.</div><h2>Somewhere, someone gets it.</h2></div><Link className="link-button" href="/humanity">Explore humanity <ArrowUpRight size={19}/></Link></div><div className="filter-row" aria-label="Filter thoughts by feeling"><button className={`chip ${filter===''?'chip-active':''}`} onClick={()=>setFilter('')}>All feelings</button>{['hopeful','love','anxious','lonely','excited','jealous'].map(slug=><button className={`chip ${filter===slug?'chip-active':''}`} key={slug} onClick={()=>setFilter(slug)}>{emotions.find(e=>e.slug===slug)!.name}</button>)}</div>{feedLoading?<div className="thought-grid">{[0,1,2].map(i=><div className="skeleton-card" key={i}/>)}</div>:feedError?<div className="notice">{feedError}</div>:feed?.thoughts.length?<div className="thought-grid">{feed.thoughts.slice(0,6).map(thought=><ThoughtCard key={thought.id} thought={thought}/>)}</div>:<div className="first-thought"><div className="first-thought-art" aria-hidden="true">“</div><div><span className="eyebrow">EVERY CONVERSATION STARTS SOMEWHERE</span><h3>A little honesty goes a long way.</h3><p>{filter?'No public thoughts with this feeling yet.':'This space is waiting for its first real thoughts.'} Share a feeling, and give someone else a chance to say “same.”</p><button className="link-button" onClick={()=>openCheckIn(filter||undefined)}>Be part of the beginning <ArrowUpRight size={19}/></button></div></div>}</section>
 <section className="now-feature page-shell"><div className="now-illustration" aria-hidden="true"><div className="sun-lines">✺</div><span>SAME TIME.<br/>DIFFERENT WORLDS.</span></div><div className="now-copy"><div className="eyebrow">A DAILY MOMENT TOGETHER</div><h2>One moment.<br/>All of us.</h2><p>Every evening at 8:30 PM India time, we pause and answer one simple question: how do you feel, right now?</p><Link href="/now" className="button button-dark">Meet Curevo Now <ArrowUpRight size={20}/></Link><span className="now-detail">20:30–21:00 IST · Join from anywhere</span></div></section>
 {!!eventData?.events.length&&<section className="page-shell events-home"><div className="section-heading"><h2>Feelings around a moment.</h2></div><div className="split-grid">{eventData.events.filter(e=>e.active).slice(0,4).map(event=><Link key={event.slug} href={`/event/${event.slug}`} className="event-preview"><span className="eyebrow">{event.sponsored?'SPONSORED PULSE':'SHARED MOMENT'}</span><h3>{event.title}</h3><p>{event.question}</p><ArrowUpRight/></Link>)}</div></section>}
 <section className="philosophy page-shell"><span className="eyebrow">A DIFFERENT KIND OF TOGETHER</span><h2>You don’t need a following<br/>to feel understood.</h2><div className="philosophy-grid"><div><span>01</span><h3>A feeling, not a profile.</h3><p>No public identities, follower counts, or performance. Your thought gets to stand on its own.</p></div><div><span>02</span><h3>Resonance, not ratings.</h3><p>A simple “same” says something a like never could: I’ve felt that, too.</p></div><div><span>03</span><h3>Yours to share. Or keep.</h3><p>Choose what becomes public. Keep the rest private. Your raw private history is never sold.</p></div></div></section>
 <section className="closing-banner"><div className="page-shell"><span className="closing-mark" aria-hidden="true">✳</span><h2>The world has room<br/>for your feeling.</h2><button className="button button-dark button-large" onClick={()=>openCheckIn()}>Join the Pulse <ArrowUpRight size={22}/></button></div></section>
 </>;
}
