'use client';
import { useEffect, useRef, useState } from 'react';
import Link from 'next/link';
import { Bookmark, Check, Copy, Download, Flag, HandHeart, Link as LinkIcon, Share2, Trash2, X } from 'lucide-react';
import type { Thought } from '@/lib/types';
import { emotionBySlug, reportReasons } from '@/lib/taxonomy';
import { api, formatTime, track } from '@/lib/client';
import { useCurevo } from './curevo-provider';

export default function ThoughtCard({thought,onDeleted,owned=false}:{thought:Thought;onDeleted?:()=>void;owned?:boolean}){
 const {savedIds,toggleSave,notify}=useCurevo();
 const [same,setSame]=useState(thought.hasSame??false),[count,setCount]=useState(thought.sameCount),[busy,setBusy]=useState(false);
 const [panel,setPanel]=useState<'share'|'report'|'delete'|null>(null),[reason,setReason]=useState('spam'),[description,setDescription]=useState(''),[hidden,setHidden]=useState(false);
 const modal=useRef<HTMLDialogElement>(null);const emotion=emotionBySlug(thought.emotion);
 useEffect(()=>{setSame(thought.hasSame??false);setCount(thought.sameCount);},[thought.hasSame,thought.sameCount]);
 useEffect(()=>{if(panel)modal.current?.showModal();else modal.current?.close();},[panel]);
 async function react(){setBusy(true);try{const res=await api<{sameCount:number;hasSame:boolean}>('/api/reactions/same',{method:'POST',body:JSON.stringify({checkInId:thought.id,active:!same})});setSame(res.hasSame);setCount(res.sameCount);track('same_clicked');window.dispatchEvent(new Event('curevo:update'));}catch(e){notify((e as Error).message);}finally{setBusy(false);}}
 async function copy(){try{await navigator.clipboard.writeText(`${window.location.origin}/t/${thought.id}`);notify('Link copied.');track('thought_shared');}catch{notify('Copy the link shown below.');}}
 async function report(){setBusy(true);try{await api('/api/reports',{method:'POST',body:JSON.stringify({checkInId:thought.id,reason,description})});notify('Report received. This thought is now hidden for you.');const old=JSON.parse(localStorage.getItem('curevo-hidden')||'[]');localStorage.setItem('curevo-hidden',JSON.stringify([...old,thought.id]));setHidden(true);setPanel(null);}catch(e){notify((e as Error).message);}finally{setBusy(false);}}
 async function remove(){setBusy(true);try{await api(`/api/checkins/${thought.id}`,{method:'DELETE'});setHidden(true);setPanel(null);notify('Your thought was deleted.');onDeleted?.();window.dispatchEvent(new Event('curevo:update'));}catch(e){notify((e as Error).message);}finally{setBusy(false);}}
 useEffect(()=>{try{setHidden(JSON.parse(localStorage.getItem('curevo-hidden')||'[]').includes(thought.id));}catch{}},[thought.id]);
 if(hidden)return null;
 const publicThought=thought.visibility!=='private'&&(!thought.moderation||thought.moderation==='approved');
 const url=typeof window!=='undefined'?`${window.location.origin}/t/${thought.id}`:'';
 return <article className="thought-card" style={{'--emotion-color':emotion.color} as React.CSSProperties}><div className="thought-meta"><Link href={`/emotion/${emotion.slug}`}><span className="thought-emotion-symbol" aria-hidden="true">{emotion.symbol}</span>{emotion.name}</Link><span>{formatTime(thought.createdAt)}</span></div><p className="thought-body">“{thought.thought}”</p><div className="thought-context"><span>{thought.cause}</span>{thought.visibility==='private'&&<span>Private</span>}{thought.moderation&&thought.moderation!=='approved'&&<span>{thought.moderation==='pending'?'Awaiting review':thought.moderation}</span>}</div><div className="thought-intention">Feeling like <span>{thought.intention.toLowerCase()}</span></div><div className="thought-actions">{publicThought&&<button className={`same-button ${same?'is-same':''}`} disabled={busy} aria-pressed={same} onClick={()=>void react()}><HandHeart size={20}/><span>same{count>0?` · ${count.toLocaleString()}`:''}</span></button>}<div className="thought-action-icons">{publicThought&&<><button className={`icon-button ${savedIds.includes(thought.id)?'is-saved':''}`} aria-label={savedIds.includes(thought.id)?'Unsave thought':'Save thought'} aria-pressed={savedIds.includes(thought.id)} onClick={()=>void toggleSave(thought).catch(e=>notify(e.message))}><Bookmark size={19} fill={savedIds.includes(thought.id)?'currentColor':'none'}/></button><button className="icon-button" aria-label="Share thought" onClick={()=>setPanel('share')}><Share2 size={19}/></button></>}{owned?<button className="icon-button" aria-label="Delete thought" onClick={()=>setPanel('delete')}><Trash2 size={18}/></button>:<button className="icon-button" aria-label="Report thought" onClick={()=>setPanel('report')}><Flag size={17}/></button>}</div></div>
 <dialog className="small-dialog" ref={modal} onCancel={()=>setPanel(null)} aria-label={panel==='share'?'Share thought':panel==='report'?'Report thought':'Delete thought'}><div className="dialog-top"><span className="eyebrow">{panel==='share'?'A FEELING WORTH SHARING':panel==='report'?'KEEP CUREVO KIND':'YOUR THOUGHT, YOUR CHOICE'}</span><button className="icon-button" aria-label="Close" onClick={()=>setPanel(null)}><X/></button></div>{panel==='share'?<><h2>Someone might get it.</h2><p>Share the feeling. The person behind it stays anonymous.</p><div className="share-preview"><span>{emotion.symbol} {emotion.name}</span><p>“{thought.thought}”</p><b>curevo.</b></div><div className="share-options"><button className="button button-dark" onClick={()=>void copy()}><Copy size={18}/> Copy link</button><a className="button button-secondary" target="_blank" rel="noopener noreferrer" href={`https://twitter.com/intent/tweet?text=${encodeURIComponent('A little of all of us in every feeling. Humanity, right now.')}&url=${encodeURIComponent(url)}`} onClick={()=>track('thought_shared')}>Share on X</a><a className="button button-secondary" target="_blank" rel="noopener noreferrer" href={`https://wa.me/?text=${encodeURIComponent(url)}`} onClick={()=>track('thought_shared')}>WhatsApp</a><a className="button button-secondary" href={`/t/${thought.id}/opengraph-image`} download="curevo-thought.png" target="_blank" rel="noopener noreferrer"><Download size={18}/> Get image</a></div><div className="copy-url"><LinkIcon size={16}/><input aria-label="Share link" readOnly value={url} onFocus={e=>e.target.select()}/></div></>:panel==='report'?<><h2>What doesn’t feel right?</h2><p>Your report is private. It helps keep this space safe.</p><label className="field-label" htmlFor={`reason-${thought.id}`}>Reason</label><select className="select" id={`reason-${thought.id}`} value={reason} onChange={e=>setReason(e.target.value)}>{reportReasons.map(r=><option key={r}>{r}</option>)}</select><label className="field-label" htmlFor={`report-${thought.id}`}>Anything else? (optional)</label><textarea className="textarea" id={`report-${thought.id}`} maxLength={280} value={description} onChange={e=>setDescription(e.target.value)}/><button className="button button-dark" disabled={busy} onClick={()=>void report()}><Flag size={18}/> {busy?'Sending…':'Report and hide'}</button></>:<><h2>Delete this thought?</h2><p>This also removes its reactions, saved references, outcome, and contribution to the Pulse. You can’t undo this.</p><div className="share-options"><button className="button button-dark" disabled={busy} onClick={()=>void remove()}><Trash2 size={18}/>Delete thought</button><button className="button button-secondary" onClick={()=>setPanel(null)}>Keep it</button></div></>}</dialog></article>;
}
