import { BookHeart, Focus, Leaf, ShieldCheck } from "lucide-react";

const principles = [
  { icon: Focus, title: "Attention with a stopping point", text: "Short focus blocks make room for one intention without turning the whole day into a performance." },
  { icon: Leaf, title: "Routines that stay flexible", text: "Helpful cues can be paused, changed, or skipped. A routine is meant to support the week, not judge it." },
  { icon: BookHeart, title: "Reflection without scoring", text: "Private notes help members notice conditions and patterns without diagnostic labels or automated wellbeing scores." },
  { icon: ShieldCheck, title: "Boundaries stated clearly", text: "Curevo is self-guided focus and wellbeing support. It does not provide diagnosis, treatment, therapy, or crisis response." },
];

export default function AboutPage() {
  return <main className="min-h-screen bg-background pb-24 pt-32 text-foreground"><div className="mx-auto max-w-6xl px-5"><p className="text-xs font-bold uppercase tracking-[0.2em] text-primary">About Curevo</p><h1 className="mt-4 max-w-4xl text-balance text-5xl font-semibold tracking-[-0.05em] sm:text-7xl">A practical place to return to your attention.</h1><p className="mt-7 max-w-3xl text-lg leading-8 text-muted-foreground">Curevo is being built for people who feel stuck, distracted, overloaded, or caught in unhelpful loops. It offers small focus practices, flexible routines, and private reflection—without pretending everyday software can replace professional care.</p><section className="mt-16 grid gap-4 sm:grid-cols-2">{principles.map((item) => <article key={item.title} className="rounded-[2rem] border bg-card p-7"><div className="grid size-11 place-items-center rounded-2xl bg-primary/10 text-primary"><item.icon className="size-5" /></div><h2 className="mt-7 text-2xl font-semibold tracking-tight">{item.title}</h2><p className="mt-3 leading-7 text-muted-foreground">{item.text}</p></article>)}</section><section className="mt-16 rounded-[2rem] bg-[#284c3c] p-8 text-white sm:p-12"><p className="text-xs font-bold uppercase tracking-[0.2em] text-emerald-100/60">Current status</p><h2 className="mt-4 text-3xl font-semibold sm:text-5xl">Still a review-only prototype.</h2><p className="mt-5 max-w-3xl leading-7 text-white/70">Public launch remains blocked until the operating entity, target users and jurisdictions, privacy ownership, accessibility evidence, security controls, crisis-language review, and support operations are approved. Review environments should use synthetic information only.</p></section></div></main>;
}
